let allMusic = [
 {
    name: "Ariana Grande, The Weeknd - Love Me Harder",
    artist: "",
    img: "music-1",
    src: "music-1",
  },
 {
    name: "Belly, The Weeknd - Might Not",
    artist: "",
    img: "music-2",
    src: "music-2",
  },
 {
    name: "Calvin Harris - Over Now (with The Weeknd)",
    artist: "",
    img: "music-3",
    src: "music-3",
  },
 {
    name: "Doja Cat, The Weeknd - You Right",
    artist: "",
    img: "music-4",
    src: "music-4",
  },
 {
    name: "Gesaffelstein - Lost in the Fire (feat. The Weeknd)",
    artist: "",
    img: "music-5",
    src: "music-5",
  },
 {
    name: "Maluma, The Weeknd - Hawái - Remix",
    artist: "",
    img: "music-6",
    src: "music-6",
  },
 {
    name: "Metro Boomin - Creepin' (with The Weeknd & 21 Savage)",
    artist: "",
    img: "music-7",
    src: "music-7",
  },
 {
    name: "NAV, The Weeknd - Some Way",
    artist: "",
    img: "music-8",
    src: "music-8",
  },
 {
    name: "Post Malone - One Right Now (with The Weeknd)",
    artist: "",
    img: "music-9",
    src: "music-9",
  },
 {
    name: "SZA, Game of Thrones - Power is Power (feat. The Weeknd & Travis Scott)",
    artist: "",
    img: "music-10",
    src: "music-10",
  },
 {
    name: "The Weeknd - A Lonely Night",
    artist: "",
    img: "music-11",
    src: "music-11",
  },
 {
    name: "The Weeknd - Acquainted",
    artist: "",
    img: "music-12",
    src: "music-12",
  },
 {
    name: "The Weeknd - After Hours",
    artist: "",
    img: "music-13",
    src: "music-13",
  },
 {
    name: "The Weeknd - Blinding Lights",
    artist: "",
    img: "music-14",
    src: "music-14",
  },
 {
    name: "The Weeknd - Call Out My Name",
    artist: "",
    img: "music-15",
    src: "music-15",
  },
 {
    name: "The Weeknd - Can't Feel My Face",
    artist: "",
    img: "music-16",
    src: "music-16",
  },
 {
    name: "The Weeknd - Die For You",
    artist: "",
    img: "music-17",
    src: "music-17",
  },
 {
    name: "The Weeknd - Earned It (Fifty Shades Of Grey) - From The 'Fifty Shades Of Grey' Soundtrack",
    artist: "",
    img: "music-18",
    src: "music-18",
  },
 {
    name: "The Weeknd - False Alarm",
    artist: "",
    img: "music-19",
    src: "music-19",
  },
 {
    name: "The Weeknd - Final Lullaby - Bonus Track",
    artist: "",
    img: "music-20",
    src: "music-20",
  },
 {
    name: "The Weeknd - Heartless",
    artist: "",
    img: "music-21",
    src: "music-21",
  },
 {
    name: "The Weeknd - High For This",
    artist: "",
    img: "music-22",
    src: "music-22",
  },
 {
    name: "The Weeknd - House Of Balloons  Glass Table Girls",
    artist: "",
    img: "music-23",
    src: "music-23",
  },
 {
    name: "The Weeknd - I Heard You’re Married (feat. Lil Wayne)",
    artist: "",
    img: "music-24",
    src: "music-24",
  },
 {
    name: "The Weeknd - In The Night",
    artist: "",
    img: "music-25",
    src: "music-25",
  },
 {
    name: "The Weeknd - In Your Eyes",
    artist: "",
    img: "music-26",
    src: "music-26",
  },
 {
    name: "The Weeknd - Missed You - Bonus Track",
    artist: "",
    img: "music-27",
    src: "music-27",
  },
 {
    name: "The Weeknd - Nothing Compares - Bonus Track",
    artist: "",
    img: "music-28",
    src: "music-28",
  },
 {
    name: "The Weeknd - Nothing Is Lost (You Give Me Strength)",
    artist: "",
    img: "music-29",
    src: "music-29",
  },
 {
    name: "The Weeknd - Nothing Without You",
    artist: "",
    img: "music-30",
    src: "music-30",
  },
 {
    name: "The Weeknd - Often",
    artist: "",
    img: "music-31",
    src: "music-31",
  },
 {
    name: "The Weeknd - Out of Time",
    artist: "",
    img: "music-32",
    src: "music-32",
  },
 {
    name: "The Weeknd - Party Monster",
    artist: "",
    img: "music-33",
    src: "music-33",
  },
 {
    name: "The Weeknd - Sacrifice",
    artist: "",
    img: "music-34",
    src: "music-34",
  },
 {
    name: "The Weeknd - Save Your Tears",
    artist: "",
    img: "music-35",
    src: "music-35",
  },
 {
    name: "The Weeknd - Secrets",
    artist: "",
    img: "music-36",
    src: "music-36",
  },
 {
    name: "The Weeknd - Take My Breath - Single Version",
    artist: "",
    img: "music-37",
    src: "music-37",
  },
 {
    name: "The Weeknd - Tell Your Friends",
    artist: "",
    img: "music-38",
    src: "music-38",
  },
 {
    name: "The Weeknd - The Hills",
    artist: "",
    img: "music-39",
    src: "music-39",
  },
 {
    name: "The Weeknd - The Morning",
    artist: "",
    img: "music-40",
    src: "music-40",
  },
 {
    name: "The Weeknd - Try Me",
    artist: "",
    img: "music-41",
    src: "music-41",
  },
 {
    name: "The Weeknd - Wasted Times",
    artist: "",
    img: "music-42",
    src: "music-42",
  },
 {
    name: "The Weeknd - Wicked Games",
    artist: "",
    img: "music-43",
    src: "music-43",
  },
 {
    name: "The Weeknd, Daft Punk - Starboy",
    artist: "",
    img: "music-44",
    src: "music-44",
  },
 {
    name: "The Weeknd, Gesaffelstein - Hurt You",
    artist: "",
    img: "music-45",
    src: "music-45",
  },
 {
    name: "The Weeknd, Gesaffelstein - I Was Never There",
    artist: "",
    img: "music-46",
    src: "music-46",
  },
 {
    name: "The Weeknd, Kendrick Lamar - Pray For Me",
    artist: "",
    img: "music-47",
    src: "music-47",
  },
 {
    name: "The Weeknd, Kendrick Lamar - Sidewalks",
    artist: "",
    img: "music-48",
    src: "music-48",
  },
 {
    name: "The Weeknd, Lana Del Rey - Stargirl Interlude",
    artist: "",
    img: "music-49",
    src: "music-49",
  },
];